services:
  clones-website-dev:
    profiles:
      - development
      - dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: clones-website-dev
    ports:
      - "5173:5173"
    volumes: 
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
    environment:
      - PUBLIC_API_URL=http://localhost:8001

  clones-website-prod:
    profiles:
      - production
      - prod
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: clones-website-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
