FROM node:lts-slim

WORKDIR /app

ENV NODE_ENV=development

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential node-gyp pkg-config python-is-python3

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

# Expose port 5173 (Vite's default port)
EXPOSE 5173
