services:
  clones-website-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: clones-website
    working_dir: /app
    tty: true
    ports:
      - "5173:5173"
    command: npm run dev
    volumes: 
      - ./:/app/
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://localhost:8001
