# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clones-site-test'
primary_region = 'lax'

[build]
  [build.args]
    VITE_API_URL = "https://api-staging.clones-ai.com"
    VITE_AUTH_ENDPOINT = "/api/v1/wallet/connect"
    VITE_DESKTOP_SCHEME = "clones-dev"
    VITE_BASESCAN_BASE_URL = "https://sepolia.basescan.org/"
    VITE_FAUCET_CONTRACT_ADDRESS = "0x6Beb3735FC332CA352301ac515AaB3a3b5160878"
    VITE_ENABLE_ANALYTICS = "false"
    VITE_WALLETCONNECT_PROJECT_ID= "f6f818cce9847f688605012eaaf4de8a"

[env]
  # Runtime environment variables (if needed)

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 10
    hard_limit = 25

  [[http_service.checks]]
    interval = "30s"
    timeout = "2s"
    method = "GET"
    path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
