# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'clones-site-prod'
primary_region = 'lax'


[build]
  [build.args]
    VITE_API_URL = "https://api.clones-ai.com"
    VITE_AUTH_ENDPOINT = "/api/v1/wallet/connect"
    VITE_DESKTOP_SCHEME = "clones-prod"
    VITE_BASESCAN_BASE_URL = "https://basescan.org/"
    VITE_FAUCET_CONTRACT_ADDRESS = "0xeD3F1269678108AB079641c4d9d59639A7047dC6"
  
  [build.secrets]
    VITE_WALLETCONNECT_PROJECT_ID = "VITE_WALLETCONNECT_PROJECT_ID"

[env]
  # Runtime environment variables (if needed)

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 100
    hard_limit = 200

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
