name: Fly Deploy (env test)

on:
  push:
    branches:
      - test

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c fly.test.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 